[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Reference environment variables in RPC URLs
[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_preconf = "${BASE_PRECONF_URL}"
base_sepolia_preconf = "${BASE_SEPOLIA_PRECONF_URL}"

# For verification
[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Optimizer settings
[profile.default.optimizer]
enabled = true
runs = 200

# See more config options at: https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md